apiVersion: apps/v1
kind: Deployment
metadata:
  name: asecgurusupermariogame-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: asecgurusupermariogame
  template:
    metadata:
      labels:
        app: asecgurusupermariogame
    spec:
      containers:
      - image: kishi720330/asecgurumariogitopsproject:2
        name: asecgurusupermariogame-container
        ports:
        - containerPort: 8080
 
---
apiVersion: v1
kind: Service
metadata:
  name: asecgurusupermariogame-service
spec:
  selector:
    app: asecgurusupermariogame
  ports:
  - protocol: TCP
    port: 8600  # <-- Change this line to your desired port
    targetPort: 8080
  type: LoadBalancer
